sopenapi: 3.0.3
info:
    title: TODO API
    version: 1.0.0
    description: API de gestion d'une TODO List.
servers:
    -   url: http://localhost:8080
        description: Serveur local de développement

tags:
    -   name: tasks
        description: Opérations sur les tâches

paths:
    /tasks:
        get:
            tags: [ tasks ]
            summary: Récupère l'ensemble des tâches
            operationId: getAllTasks
            parameters:
                -   in: query
                    name: todo-only
                    required: false
                    description: Indique s'il faut seulement récupérer les tâches à réaliser.
                    schema:
                        type: boolean
                        default: false
            responses:
                '200':
                    description: Liste des tâches récupérée avec succès
                    content:
                        application/json:
                            schema:
                                type: array
                                items:
                                    $ref: '#/components/schemas/Task'
                '204':
                    description: Pas de résultat (aucune tâche ne correspond)

        post:
            tags: [ tasks ]
            summary: Créer une tâche
            operationId: createTask
            requestBody:
                required: true
                content:
                    application/json:
                        schema:
                            $ref: '#/components/schemas/Task'
            responses:
                '201':
                    description: Tâche créée avec succès
                    headers:
                        Location:
                            description: URL de la ressource créée
                            schema:
                                type: string
                                example: /tasks/1
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/Task'
        delete:
            tags: [ tasks ]
            summary: Supprimer TOUTES les tâches (Bonus)
            description: Supprime l'intégralité des tâches stockées en mémoire.
            operationId: deleteAllTasks
            responses:
                '204':
                    description: Toutes les tâches ont été supprimées avec succès

    /tasks/{id}:
        parameters:
            -   in: path
                name: id
                required: true
                description: Identifiant numérique de la tâche
                schema:
                    type: integer
                    minimum: 1
        get:
            tags: [ tasks ]
            summary: Récupérer une tâche
            description: Récupérer une tâche par son identifiant
            operationId: getTaskById
            responses:
                '200':
                    description: Tâche trouvée avec succès
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/Task'
                '404':
                    description: Tâche non trouvée

        put:
            tags: [ tasks ]
            summary: Modifier une tâche
            description: Modifie une tâche existante à partir d’un JSON.
            operationId: updateTask
            requestBody:
                required: true
                content:
                    application/json:
                        schema:
                            $ref: '#/components/schemas/Task'
            responses:
                '204':
                    description: Tâche modifiée avec succès (aucun contenu retourné)
                '404':
                    description: Tâche non trouvée

        delete:
            tags: [ tasks ]
            summary: Supprimer une tâche
            description: Supprime une tâche par son identifiant.
            operationId: deleteTask
            responses:
                '204':
                    description: Tâche supprimée avec succès (aucun contenu retourné)
                '404':
                    description: Tâche non trouvée

    /tasks/count:
        get:
            tags: [ tasks ]
            summary: Compter le nombre de tâches (Bonus)
            description: Retourne le nombre total de tâches sous la forme d'un entier brut.
            operationId: countTasks
            responses:
                '200':
                    description: Nombre récupéré avec succès
                    content:
                        text/plain:
                            schema:
                                type: integer
                                example: 3

components:
    schemas:
        Task:
            type: object
            description: Représentation d'une tâche
            properties:
                id:
                    type: integer
                    example: 1
                title:
                    type: string
                    nullable: false
                    example: Acheter du lait
                description:
                    type: string
                    nullable: true
                    example: 2L demi-écrémé
                done:
                    type: boolean
                    nullable: false
                    example: false
            required:
                - id
                - title